import type { Activity, ActivityImage, PeriodUnit, Today } from "@lighthouse/shared";
import { apiBaseUrl, deviceToken } from "./config";

// How long to wait before deciding the API is not going to answer. Long enough
// for a phone waking its Wi-Fi, short enough that a television with no route to
// the server falls back to its cache while someone is still looking at it.
const TIMEOUT_MS = 5000;

// A request that did not succeed, with enough detail for the UI to tell "the
// server said no" from "the server was not there" — the first is worth showing
// as an error, the second is worth falling back to the cache for.
export class ApiError extends Error {
  constructor(
    message: string,
    // Absent when the request never got an answer at all.
    readonly status?: number,
  ) {
    super(message);
    this.name = "ApiError";
  }

  // Nothing on the other end: no network, server down, wrong address.
  get isOffline(): boolean {
    return this.status === undefined;
  }

  // The device token is missing or wrong — the one failure a user cannot fix
  // from the sofa, so it has to be said plainly rather than retried forever.
  get isUnauthorized(): boolean {
    return this.status === 401;
  }
}

export interface ActivityInput {
  id: string;
  title: string;
  every: number;
  unit: PeriodUnit;
  image?: ActivityImage;
}

async function request<T>(path: string, init: RequestInit = {}): Promise<T> {
  const token = deviceToken();
  let response: Response;

  try {
    response = await fetch(`${apiBaseUrl()}${path}`, {
      ...init,
      signal: AbortSignal.timeout(TIMEOUT_MS),
      headers: {
        ...(init.body === undefined ? {} : { "Content-Type": "application/json" }),
        ...(token === "" ? {} : { Authorization: `Bearer ${token}` }),
        ...init.headers,
      },
    });
  } catch (cause) {
    throw new ApiError(cause instanceof Error ? cause.message : "Request failed");
  }

  if (!response.ok) {
    throw new ApiError(`${init.method ?? "GET"} ${path} failed`, response.status);
  }
  // 204, which DELETE answers with.
  if (response.status === 204) return undefined as T;

  return (await response.json()) as T;
}

const body = (value: unknown): RequestInit => ({ body: JSON.stringify(value) });

export const api = {
  activities: (): Promise<Activity[]> => request("/activities"),

  today: (): Promise<Today> => request("/today"),

  // The id is generated by the client, which is what lets a request that is
  // retried after an unclear failure land on the row it already made.
  save: (input: ActivityInput): Promise<Activity> =>
    request("/activities", { method: "POST", ...body(input) }),

  update: (id: string, patch: Omit<ActivityInput, "id">): Promise<Activity> =>
    request(`/activities/${encodeURIComponent(id)}`, { method: "PATCH", ...body(patch) }),

  // The timestamp is sent rather than left to the server, so a press is filed
  // under when it happened and not under when the request arrived.
  markDone: (id: string, doneAt: string): Promise<Activity> =>
    request(`/activities/${encodeURIComponent(id)}/done`, {
      method: "POST",
      ...body({ doneAt }),
    }),

  remove: (id: string): Promise<void> =>
    request(`/activities/${encodeURIComponent(id)}`, { method: "DELETE" }),
};
